/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.model.Jogo;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.SwingConstants;

/**
 *
 * @author Guilherme Lourenço
 */
public class TelaInfoJogo extends javax.swing.JFrame {

    /**
     * Creates new form TelaInfoJogo
     * Commit
     */
    public TelaInfoJogo() {
        initComponents();
    }
    
    public TelaInfoJogo(Jogo jogo){
        this();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.getContentPane().setBackground(Color.WHITE);
        this.painel1.setBackground(Color.WHITE);
        Font f = InicioProjeto.getFonte(36);
        painel1.setFont(f);
        lbTime1.setIcon(jogo.getTime1().getEscudo());
        lbTime1.setFont(f);
        lbTime1.setHorizontalAlignment(SwingConstants.CENTER);
        lbTime1.setVerticalAlignment(SwingConstants.CENTER);
        lbTime2.setIcon(jogo.getTime2().getEscudo());
        lbTime2.setFont(f);
        lbTime2.setHorizontalAlignment(SwingConstants.CENTER);
        lbTime2.setVerticalAlignment(SwingConstants.CENTER);
        lbGolsTime1.setText(String.valueOf(jogo.getGolTime1()));
        lbGolsTime1.setFont(f);
        lbGolsTime1.setHorizontalAlignment(SwingConstants.CENTER);
        lbGolsTime1.setVerticalAlignment(SwingConstants.CENTER);
        lbGolsTime2.setText(String.valueOf(jogo.getGolTime2()));
        lbGolsTime2.setFont(f);
        lbGolsTime2.setHorizontalAlignment(SwingConstants.CENTER);
        lbGolsTime2.setVerticalAlignment(SwingConstants.CENTER);
        lbFinalizacoesTime1.setText(String.valueOf(jogo.getFinalizacaoTime1()));
        lbFinalizacoesTime1.setFont(f);
        lbFinalizacoesTime1.setHorizontalAlignment(SwingConstants.CENTER);
        lbFinalizacoesTime1.setVerticalAlignment(SwingConstants.CENTER);
        lbFinalizacoesTime2.setText(String.valueOf(jogo.getFinalizacaoTime2()));
        lbFinalizacoesTime2.setFont(f);
        lbFinalizacoesTime2.setHorizontalAlignment(SwingConstants.CENTER);
        lbFinalizacoesTime2.setVerticalAlignment(SwingConstants.CENTER);
        lbPosseTime1.setText(String.valueOf((int)jogo.getPosseDeBolaTime1()) + "%");
        lbPosseTime1.setFont(f);
        lbPosseTime1.setHorizontalAlignment(SwingConstants.CENTER);
        lbPosseTime1.setVerticalAlignment(SwingConstants.CENTER);
        lbPosseTime2.setText(String.valueOf((int)jogo.getPosseDeBolaTime2()) + "%");
        lbPosseTime2.setFont(f);
        lbPosseTime2.setHorizontalAlignment(SwingConstants.CENTER);
        lbPosseTime2.setVerticalAlignment(SwingConstants.CENTER);
        
        lbTextoGols.setFont(f);
        lbTextoFinalizacoes.setFont(f);
        lbTextoPosse.setFont(f);
        this.setResizable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel1 = new javax.swing.JPanel();
        lbTextoGols = new javax.swing.JLabel();
        lbTextoFinalizacoes = new javax.swing.JLabel();
        lbTextoPosse = new javax.swing.JLabel();
        lbTime1 = new javax.swing.JLabel();
        lbTime2 = new javax.swing.JLabel();
        lbGolsTime1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lbGolsTime2 = new javax.swing.JLabel();
        lbFinalizacoesTime1 = new javax.swing.JLabel();
        lbFinalizacoesTime2 = new javax.swing.JLabel();
        lbPosseTime1 = new javax.swing.JLabel();
        lbPosseTime2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacoes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("FIFA Welcome", 0, 18))); // NOI18N

        lbTextoGols.setFont(new java.awt.Font("FIFA Welcome", 0, 36)); // NOI18N
        lbTextoGols.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTextoGols.setText("Gols");

        lbTextoFinalizacoes.setFont(new java.awt.Font("FIFA Welcome", 0, 36)); // NOI18N
        lbTextoFinalizacoes.setText("Finalizacoes");

        lbTextoPosse.setFont(new java.awt.Font("FIFA Welcome", 0, 36)); // NOI18N
        lbTextoPosse.setText("Posse de Bola");

        lbTime1.setForeground(new java.awt.Color(255, 255, 255));
        lbTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbTime2.setForeground(new java.awt.Color(255, 255, 255));
        lbTime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbGolsTime1.setFont(new java.awt.Font("FIFA Welcome", 0, 36)); // NOI18N
        lbGolsTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGolsTime1.setText("_");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("X");

        lbGolsTime2.setFont(new java.awt.Font("FIFA Welcome", 0, 36)); // NOI18N
        lbGolsTime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGolsTime2.setText("_");

        lbFinalizacoesTime1.setFont(new java.awt.Font("FIFA Welcome", 0, 36)); // NOI18N
        lbFinalizacoesTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFinalizacoesTime1.setText("_");

        lbFinalizacoesTime2.setFont(new java.awt.Font("FIFA Welcome", 0, 36)); // NOI18N
        lbFinalizacoesTime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFinalizacoesTime2.setText("_");

        lbPosseTime1.setFont(new java.awt.Font("FIFA Welcome", 0, 36)); // NOI18N
        lbPosseTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPosseTime1.setText("_");

        lbPosseTime2.setFont(new java.awt.Font("FIFA Welcome", 0, 36)); // NOI18N
        lbPosseTime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPosseTime2.setText("_");

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbFinalizacoesTime1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(lbGolsTime1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbPosseTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel1Layout.createSequentialGroup()
                        .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTextoGols, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTextoPosse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(painel1Layout.createSequentialGroup()
                                        .addComponent(lbTextoFinalizacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(45, 45, 45)))
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbPosseTime2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lbFinalizacoesTime2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbGolsTime2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTime2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGolsTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTextoGols, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGolsTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFinalizacoesTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbFinalizacoesTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTextoFinalizacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPosseTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPosseTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTextoPosse, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInfoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInfoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInfoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInfoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInfoJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel lbFinalizacoesTime1;
    private javax.swing.JLabel lbFinalizacoesTime2;
    private javax.swing.JLabel lbGolsTime1;
    private javax.swing.JLabel lbGolsTime2;
    private javax.swing.JLabel lbPosseTime1;
    private javax.swing.JLabel lbPosseTime2;
    private javax.swing.JLabel lbTextoFinalizacoes;
    private javax.swing.JLabel lbTextoGols;
    private javax.swing.JLabel lbTextoPosse;
    private javax.swing.JLabel lbTime1;
    private javax.swing.JLabel lbTime2;
    private javax.swing.JPanel painel1;
    // End of variables declaration//GEN-END:variables
}
